### ISSUE TITLE
Ray Tracing support (spin-off renderer)

### ISSUE THREAD

**Issue by capitalknew** [Vault16Software/Blue-Flame-Engine#1]
Hello. I'm working on ray tracing core. It unofficially implemented to Neverball and Minecraft (MCP mod). I propose add ray tracing support for this engine as spin-off renderer (alongside with OpenGL and DirectX).

**Comment by Vault16Software** [comment]
That is a good idea. I will add it to the "Feature Request" list on Trello and I will work on it at some point.

Cheers.
